// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://tvpnjarioubhoffsmqxk.supabase.co";

const FALLBACK_KEY =
  typeof atob !== "undefined"
    ? atob("c2Jfc2VjcmV0X21hZ0g4UzBiSHFQRjJ6MklZLVBCTlFfczdHUUJxTTQ=")
    : "";

const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_PUBLISHABLE_KEY =
  envKey && !envKey.includes("placeholder")
    ? envKey
    : FALLBACK_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});